from sqlalchemy import Column, String, Integer, FLOAT

from app.database import Base


class tbCell(Base):
    __tablename__ = "tbCell"

    CITY = Column(String)
    SECTOR_ID = Column(String, primary_key=True, unique=True, index=True)
    SECTOR_NAME = Column(String, nullable=False)
    ENODEBID = Column(Integer, index=True)
    ENODEB_NAME = Column(String, nullable=False)
    EARFCN = Column(Integer, nullable=False)
    PCI = Column(Integer)
    PSS = Column(Integer)
    SSS = Column(Integer)
    TAC = Column(Integer)
    VENDOR = Column(String)
    LONGITUDE = Column(FLOAT)
    LATITUDE = Column(FLOAT)
    STYLE = Column(String)
    AZIMUTH = Column(FLOAT, nullable=False)
    HEIGHT = Column(FLOAT)
    ELECTTILT = Column(FLOAT)
    MECHTILT = Column(FLOAT)
    TOTLETILT = Column(FLOAT, nullable=False)


class tbKPI(Base):
    __tablename__ = "tbKPI"

    StartTime = Column(String, primary_key=True)
    ENODEB_NAME = Column(String)
    SECTOR_DESCRIPTION = Column(String)
    SECTOR_NAME = Column(String, primary_key=True)
    RCCConnSUCC = Column(Integer)
    RCCConnATT = Column(Integer)
    RCCConnRATE = Column(FLOAT)



class tbMROData(Base):
    __tablename__ = "tbMROData"

    TimeStamp = Column(String, primary_key=True)
    ServingSector = Column(String, primary_key=True)
    InterferingSector = Column(String, primary_key=True)
    LteScRSRP = Column(FLOAT)
    LteNcRSRP = Column(FLOAT)
    LteNcEarfcn = Column(Integer)
    LteNcPci = Column(Integer)


class tbPRB(Base):
    __tablename__ = "tbPRB"

    StartTime = Column(String)
    ENODEB_NAME = Column(String, primary_key=True)
    SECTOR_DESCRIPTION = Column(String)
    SECTOR_NAME = Column(String)
    AvgNoise0 = Column(FLOAT)
    AvgNoise1 = Column(FLOAT)
    AvgNoise2 = Column(FLOAT)
    AvgNoise3 = Column(FLOAT)
    AvgNoise4 = Column(FLOAT)
    AvgNoise5 = Column(FLOAT)
    AvgNoise6 = Column(FLOAT)
    AvgNoise7 = Column(FLOAT)
    AvgNoise8 = Column(FLOAT)
    AvgNoise9 = Column(FLOAT)
    AvgNoise10 = Column(FLOAT)
    AvgNoise11 = Column(FLOAT)
    AvgNoise12 = Column(FLOAT)
    AvgNoise13 = Column(FLOAT)
    AvgNoise14 = Column(FLOAT)
    AvgNoise15 = Column(FLOAT)
    AvgNoise16 = Column(FLOAT)
    AvgNoise17 = Column(FLOAT)
    AvgNoise18 = Column(FLOAT)
    AvgNoise19 = Column(FLOAT)
    AvgNoise20 = Column(FLOAT)
    AvgNoise21 = Column(FLOAT)
    AvgNoise22 = Column(FLOAT)
    AvgNoise23 = Column(FLOAT)
    AvgNoise24 = Column(FLOAT)
    AvgNoise25 = Column(FLOAT)
    AvgNoise26 = Column(FLOAT)
    AvgNoise27 = Column(FLOAT)
    AvgNoise28 = Column(FLOAT)
    AvgNoise29 = Column(FLOAT)
    AvgNoise30 = Column(FLOAT)
    AvgNoise31 = Column(FLOAT)
    AvgNoise32 = Column(FLOAT)
    AvgNoise33 = Column(FLOAT)
    AvgNoise34 = Column(FLOAT)
    AvgNoise35 = Column(FLOAT)
    AvgNoise36 = Column(FLOAT)
    AvgNoise37 = Column(FLOAT)
    AvgNoise38 = Column(FLOAT)
    AvgNoise39 = Column(FLOAT)
    AvgNoise40 = Column(FLOAT)
    AvgNoise41 = Column(FLOAT)
    AvgNoise42 = Column(FLOAT)
    AvgNoise43 = Column(FLOAT)
    AvgNoise44 = Column(FLOAT)
    AvgNoise45 = Column(FLOAT)
    AvgNoise46 = Column(FLOAT)
    AvgNoise47 = Column(FLOAT)
    AvgNoise48 = Column(FLOAT)
    AvgNoise49 = Column(FLOAT)
    AvgNoise50 = Column(FLOAT)
    AvgNoise51 = Column(FLOAT)
    AvgNoise52 = Column(FLOAT)
    AvgNoise53 = Column(FLOAT)
    AvgNoise54 = Column(FLOAT)
    AvgNoise55 = Column(FLOAT)
    AvgNoise56 = Column(FLOAT)
    AvgNoise57 = Column(FLOAT)
    AvgNoise58 = Column(FLOAT)
    AvgNoise59 = Column(FLOAT)
    AvgNoise60 = Column(FLOAT)
    AvgNoise61 = Column(FLOAT)
    AvgNoise62 = Column(FLOAT)
    AvgNoise63 = Column(FLOAT)
    AvgNoise64 = Column(FLOAT)
    AvgNoise65 = Column(FLOAT)
    AvgNoise66 = Column(FLOAT)
    AvgNoise67 = Column(FLOAT)
    AvgNoise68 = Column(FLOAT)
    AvgNoise69 = Column(FLOAT)
    AvgNoise70 = Column(FLOAT)
    AvgNoise71 = Column(FLOAT)
    AvgNoise72 = Column(FLOAT)
    AvgNoise73 = Column(FLOAT)
    AvgNoise74 = Column(FLOAT)
    AvgNoise75 = Column(FLOAT)
    AvgNoise76 = Column(FLOAT)
    AvgNoise77 = Column(FLOAT)
    AvgNoise78 = Column(FLOAT)
    AvgNoise79 = Column(FLOAT)
    AvgNoise80 = Column(FLOAT)
    AvgNoise81 = Column(FLOAT)
    AvgNoise82 = Column(FLOAT)
    AvgNoise83 = Column(FLOAT)
    AvgNoise84 = Column(FLOAT)
    AvgNoise85 = Column(FLOAT)
    AvgNoise86 = Column(FLOAT)
    AvgNoise87 = Column(FLOAT)
    AvgNoise88 = Column(FLOAT)
    AvgNoise89 = Column(FLOAT)
    AvgNoise90 = Column(FLOAT)
    AvgNoise91 = Column(FLOAT)
    AvgNoise92 = Column(FLOAT)
    AvgNoise93 = Column(FLOAT)
    AvgNoise94 = Column(FLOAT)
    AvgNoise95 = Column(FLOAT)
    AvgNoise96 = Column(FLOAT)
    AvgNoise97 = Column(FLOAT)
    AvgNoise98 = Column(FLOAT)
    AvgNoise99 = Column(FLOAT)
